---
title: "Assignment 1: Introduction"
author: "Asreeta Ushasri"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have no prior experience with R or Git. I have taken an introductory statistics course which aided my understanding of data analytics. As a Public Relationships specialist, I learned about the cybersecurity concepts and the importance of software updates. However, this class will be my first technical introduction into data analytics.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident about the support systems in this course. The instructions in the modules are extremely helpful and provide step by step tools to understand each task. I also have many opporunities to ask questions through slack and office hours.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am apprehensive about my ability to learn coding languages, but I am also eager to learn how to use Git and R. I recently joined a Bass Connections project, which aims to use drones and GIS tools to monitor elephant health and movement. I am excited for the opportunity to apply data analytics to my Bass Connections team.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/aushasri/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
